const { STATES } = require("./chat/chatState");
const {
  createChatSession,
  getChatSessions,
  getChatMessages,
  getOwnedSession,
  getOrCreateSession,
  saveSession,
  resetSession,
} = require("./chat/chatSessionStore");
const {
  handleChatMessage,
  handleStart,
  handleAskLocation,
  handleAskConsultationType,
  handleWaitSelectDoctor,
  handleWaitSelectSlot,
  handleAskPatientName,
  handleAskPatientPhone,
  handleAskPatientEmail,
  handleConfirmBooking,
  createBookingFromSession,
  formatDoctorsReply,
  formatSlotsReply,
  formatConfirmReply,
} = require("./chat/chatConversationFlow");
const {
  findDoctorsFromCollectedInfo,
  getAvailableSlotsForDoctor,
} = require("./chat/chatDoctorSearchService");
const {
  parseSelectionNumber,
  normalizeText,
  parsePreferredDate,
  isConfirmMessage,
  isCancelMessage,
  normalizePhone,
  isValidPhone,
  normalizeEmail,
  isValidEmail,
} = require("./chat/chatUtils");

module.exports = {
  STATES,
  createChatSession,
  getChatSessions,
  getChatMessages,
  getOwnedSession,
  getOrCreateSession,
  saveSession,
  resetSession,
  handleChatMessage,
  handleStart,
  handleAskLocation,
  handleAskConsultationType,
  handleWaitSelectDoctor,
  handleWaitSelectSlot,
  handleAskPatientName,
  handleAskPatientPhone,
  handleAskPatientEmail,
  handleConfirmBooking,
  findDoctorsFromCollectedInfo,
  getAvailableSlotsForDoctor,
  createBookingFromSession,
  parseSelectionNumber,
  normalizeText,
  parsePreferredDate,
  isConfirmMessage,
  isCancelMessage,
  normalizePhone,
  isValidPhone,
  normalizeEmail,
  isValidEmail,
  formatDoctorsReply,
  formatSlotsReply,
  formatConfirmReply,
};
