const assert = require("assert");
const crypto = require("crypto");
process.env.SEPAY_WEBHOOK_AUTH_TYPE = "HMAC";
process.env.SEPAY_WEBHOOK_SECRET = "test-secret";
process.env.SEPAY_PAYMENT_EXPIRE_MINUTES = "15";
const { PAYMENT_STATUS, buildPaymentCode, buildQrCodeUrl, extractPaymentCode, getPaymentExpiryAt, getPublicPaymentStatus, getSePayTransactionId, isPaymentExpired, shouldAssignOnlineBookingQueue, verifySePaySignature } = require("./paymentService");

const rawBody = '{"id":92704,"gateway":"Vietcombank","transactionDate":"2024-07-02 11:08:33","accountNumber":"1017588888","subAccount":"","code":"SEVN63DC8E5C","content":"SEVN63DC8E5C chuyen tien","transferType":"in","description":"NGUYEN VAN A chuyen tien","transferAmount":5000000,"accumulated":105000000,"referenceCode":"FT24012345678"}';
const timestamp = String(Math.floor(Date.now() / 1000));
const signature = `sha256=${crypto.createHmac("sha256", process.env.SEPAY_WEBHOOK_SECRET).update(`${timestamp}.${rawBody}`).digest("hex")}`;
assert.match(buildPaymentCode(12, "APM"), /^APM12[A-F0-9]{8}$/);
assert.match(buildQrCodeUrl({ accountNumber: "123", bankName: "Vietcombank", amount: 10000, paymentCode: "APM12" }), /acc=123/);
assert.equal(getSePayTransactionId({ id: 0 }), "0");
const paymentCode = "APM135FB554B32";
const actualSePayPayload = { gateway: "TPBank", transactionDate: "2026-07-17 03:17:17", accountNumber: "99999010203", code: null, content: paymentCode, transferType: "in", description: `BankAPINotify ${paymentCode}`, transferAmount: 10000, referenceCode: "391ITC1261980020", id: 68570744 };
assert.equal(extractPaymentCode(actualSePayPayload), paymentCode);
assert.equal(extractPaymentCode({ code: ` ${paymentCode.toLowerCase()} `, content: "ignored" }), paymentCode);
assert.equal(extractPaymentCode({ code: null, content: "ignored", description: `BankAPINotify ${paymentCode}` }), paymentCode);
assert.equal(extractPaymentCode({ code: null, content: "unrelated APMCODE", description: "no payment code" }), null);
assert.equal(verifySePaySignature({ rawBody, timestamp, signature }), true);
assert.equal(verifySePaySignature({ rawBody, timestamp, signature: "sha256=bad" }), false);
const confirmedOnlineBooking = { id: 1, doctorId: 2, date: "2026-07-18", appointmentTypeId: "AT2", statusId: "S8" };
assert.equal(shouldAssignOnlineBookingQueue({ booking: confirmedOnlineBooking, payment: { statusId: PAYMENT_STATUS.PAID_PENDING_DOCTOR } }), true);
assert.equal(shouldAssignOnlineBookingQueue({ booking: confirmedOnlineBooking, payment: { statusId: PAYMENT_STATUS.COMPLETED } }), true);
assert.equal(shouldAssignOnlineBookingQueue({ booking: { ...confirmedOnlineBooking, statusId: "S2" }, payment: { statusId: PAYMENT_STATUS.PAID_PENDING_DOCTOR } }), false);
assert.equal(shouldAssignOnlineBookingQueue({ booking: confirmedOnlineBooking, payment: { statusId: PAYMENT_STATUS.PENDING } }), false);
assert.equal(shouldAssignOnlineBookingQueue({ booking: { ...confirmedOnlineBooking, statusId: "S6" }, payment: { statusId: PAYMENT_STATUS.PAID_PENDING_DOCTOR } }), false);
assert.equal(shouldAssignOnlineBookingQueue({ booking: confirmedOnlineBooking, payment: { statusId: PAYMENT_STATUS.REFUNDED } }), false);
assert.equal(getPublicPaymentStatus(PAYMENT_STATUS.COMPLETED), "PAID");
const createdAt = new Date("2026-07-17T10:00:00.000Z");
assert.equal(getPaymentExpiryAt({ createdAt }).toISOString(), "2026-07-17T10:15:00.000Z");
assert.equal(isPaymentExpired({ createdAt }, undefined, new Date("2026-07-17T10:15:00.000Z").getTime()), true);
assert.equal(isPaymentExpired({ createdAt }, undefined, new Date("2026-07-17T10:14:59.000Z").getTime()), false);
console.log("paymentService test passed");
