services:
  mysql:
    image: mysql:8.4
    container_name: clinic_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: kham_benh_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - clinic_mysql_data:/var/lib/mysql

volumes:
  clinic_mysql_data:
