-- Store app timestamps as local DATETIME values and keep the migration session in Vietnam time.
-- Run this once on databases that were created with TIMESTAMP audit columns.
SET time_zone = '+07:00';

ALTER TABLE `lookup`
  MODIFY `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `users`
  MODIFY `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `specialty`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `clinic`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `clinic_department`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `doctor_info`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `schedule`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `booking`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `booking_queue_sequence`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `booking_queue`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `examination_visit`
  MODIFY `startedAt` datetime NULL DEFAULT NULL,
  MODIFY `completedAt` datetime NULL DEFAULT NULL,
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `video_consultation_session`
  MODIFY `startedAt` datetime NULL DEFAULT NULL,
  MODIFY `endedAt` datetime NULL DEFAULT NULL,
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `patient_profile`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `medical_record`
  MODIFY `closedAt` datetime NULL DEFAULT NULL,
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `paraclinical_result`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `prescription`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `prescription_item`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `post`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `post_category`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `post_category_detail`
  MODIFY `createdAt` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updatedAt` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
